### ISSUE TITLE
Notify about compilation errors

### ISSUE THREAD

**Issue by lmartins** [mikaelbr/gulp-notify#1]
Is it possible to have it emit notification when sass compilation fails in a watcher like this:

```
gulp.task('default', function () {
  server.listen(35729, function (err) {
    if (err) return console.log(err);

    gulp.watch('sass/**/*.scss', function () {
        gulp.run('sass');
    });
  });
});
```

**Comment by MiguelDebruyne** [comment]
Digging up an old thread here but it's relevant

Is this still the way to go? Or can you put both functions inside one function nowadays?
I find writing double handlers on every task that needs error handling a bit tedious and it's cluttering the code. 

Would love to have something like this:

```javascript
var displayErrorMessage = function (err) {
    console.log('Error:', err);
    notify.onError();
};

var b = require('browserify');

gulp.task('dosomething', function () {
    b()    
    .bundle()
    .on('error', displayErrorMessage)
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('./src/js/'))
})
```
