### ISSUE TITLE
gulp-notify throws on errors on messages involving interpolated expressions

### ISSUE THREAD

**Issue by scmart** [mikaelbr/gulp-notify#106]
An error is being thrown by the MessageTemplate function generated in generate function of lib/report.js.

The message is as follows:

SyntaxError:
/PATH_REMOVED/rules.js:
Unexpected token (507:80)
[0m  505 |             validate[1m:[22m [36mfunction[39m[34m[1m([22m[39mforce[34m[1m)[22m[39m [32m{[39m
  506 |                 let myNames [1m=[22m [36mthis[39m[1m.[22mnames[1m;[22m

> 507 |                 let selector [1m=[22m $[34m[1m([22m[39mnames[1m.[22mmap[34m[1m([22m[39mname [1m=>[22m [31m`[name="${name}"]`[39m[34m[1m)[22m[39m[1m.[22mjoin[34m[1m([22m[39m[31m','[39m[34m[1m)[22m[39m[1m;[22m
>       |                                                                                 ^
>   508 |                 [36mif[39m [34m[1m([22m[39m$[34m[1m([22m[39mselector[34m[1m)[22m[39m[1m.[22mlength [1m!==[22m names[1m.[22mlength[34m[1m)[22m[39m [32m{[39m
>   509 |                     [90m// we dont have all the elements of the group, dont validate[39m
>   510 |                     [36mreturn[39m [36mtrue[39m[1m;[22m[0m
>     at Parser.pp.raise (… FULL_STACK_REMOVED

What's occurring is that the lodash template method is seeing ${name} in the message and thinking it needs to be replaced, but of course there is nothing to replace it with, it should not be replaced.  I don't know gulp-notify anywhere near enough to understand what the purposes of this template call are and what the best way to fix this is.  My limited testing suggests that this is an issue anywhere there is an error message that includes es6 interpolated expressions in template literals.

**Comment by mrDinckleman** [comment]
I met the same issue. I am using gulp-ejs plugin for rendering ejs-files, and when the error occurs, notifier can't send message.

gulpfile.js:
```
...
.pipe(ejs())
.on('error', notify.onError(function (error) {
  return {
    title: 'Views',
    message: error.message
   }
}))
...
```
error.message:
```
'\\app\\views\\index.ejs:4\n    2| <%- include(\'partials/_header\') %>\n    3| <section>Content</section>\n >> 4| <%- include(\'partials/_footer1\') %>\n    5| <%- include(\'partials/_foot\') %>\n    6| \n\nCould not find the include file "partials/_footer1"'
```
Message in console (toast is not shown):
```
gulp-notify: [Error running notifier] Could not send message: include is not defined
```
Obviously, error.message somehow passed to the gulp-ejs again because its see own syntax (<%- %>) and trying to execute this code.
I changed error handler to:
```
.on('error', notify.onError(function (error) {
  return '<%= temp %>';
}))
```
And notifier said:
```
gulp-notify: [Error running notifier] Could not send message: temp is not defined
```
If I change error handler to:
```
.on('error', notify.onError('Error: <%= error.message %>'))
```
notifiers works as it should.
