### ISSUE TITLE
kCFURLVolumeIsAutomountedKey missing, error in plugin after macOS Sierra

### ISSUE THREAD

**Issue by natbatwat** [mikaelbr/gulp-notify#113]
I'm running macOS Sierra V10.12, just updated today. 

Getting this error message upon running Gulp task:
```[12:56:04] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    2016-09-21 12:56:04.205 terminal-notifier[11630:142879] kCFURLVolumeIsAutomountedKey missing for file:///private/var/setup/: Error Domain=NSCocoaErrorDomain Code=260 "The file “setup” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///private/var/setup/, NSFilePath=/private/var/setup, NSUnderlyingError=0x7ffe4d632930 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}```

**Comment by mikaelbr** [comment]
Hi! I'll check this out later today when I update my mac. I didn't have any issues with macOS Sierra Beta 7, as far as I know.

**Comment by BenConstable** [comment]
I was also having this issue, and after installing the Xcode CLI tools via `xcode-select --install` and restarting my machine I stopped receiving the error. It may have just been the restart that sorted it, as installing the CLI tools alone didn't solve the problem.

Hopefully it'll work for you too - apologies if not!

**Comment by mikaelbr** [comment]
I wasn't able to reproduce this. Maybe it's after updating xcode and having to accept user agreements for it?

Great insight @BenConstable !

**Comment by natbatwat** [comment]
@BenConstable works like a charm! Restarting my computer was the step I missed. Thanks!

@mikaelbr thanks!

**Comment by BenConstable** [comment]
No worries, glad it worked for you.
