### ISSUE TITLE
Time in UTC

### ISSUE THREAD

**Issue by Salfai77210** [mikaelbr/gulp-notify#117]
Hi,

My issue is simple but i don't have a clue on how to deal with it 🤕 

# Issue
There is an example: (in french)
```bash
dev@dev ~/test $> date
lundi 6 mars 2017, 17:23:35 (UTC+0100)
dev@dev ~/test $> gulp
[16:23:40] gulp-notify: [SASS Compiled] Your CSS files are ready sir.
```

```js
[...]
.pipe($.notify({
      title: "SASS Compiled",
      message: "Your CSS files are ready sir.",
      onLast: true
    })
[...]
```

You can see that the time sent by gulp-notify is the UTC time.
Is there a solution to make `gulp-notify` use my TimeZone instead ?
Or should i just add 1 hour to my time ⭕️✖️❌  

# Support information

- Using virtualisation Guest via VMware on Windows 10 PRO Host
- Time synchronisation with host via [VMware Tools](https://pubs.vmware.com/vsphere-50/index.jsp#com.vmware.vmtools.install.doc/GUID-C0D8326A-B6E7-4E61-8470-6C173FDDF656.html?resultof=%2522%2574%2569%256d%2565%2573%2579%256e%2563%2522%2520)
```bash
$> vmware-toolbox-cmd timesync status
Enabled
```
- OS Ubuntu 16.04 Server
- Using corporate proxy

Best regards,

**Comment by mikaelbr** [comment]
Hi!

Sorry for the very late respons. See https://github.com/mikaelbr/gulp-notify/blob/master/lib/extra_api.js#L67-L70

You can override the logger to your own logger using local time zones.

**Comment by Salfai77210** [comment]
Thanks a lot
