### ISSUE TITLE
Notification doesn work

### ISSUE THREAD

**Issue by trip1e** [mikaelbr/gulp-notify#119]
# Hello!

I have this code:
```
gulp.task("click", function () {
  return gulp.src("1.txt")
      .pipe(notify({ message: 'Hello 1', wait: true }))
});

```

It works but only in terminal. I don´t get notification. 

_I´m using Windows 10_

Thanks for help!

**Comment by Alecto** [comment]
Notifications stopped working a few days ago after the last update of Windows 10.

**Comment by mikaelbr** [comment]
See https://github.com/mikaelbr/node-notifier/issues/208

**Comment by mikaelbr** [comment]
Error upstream. Can't fix here.

**Comment by Alecto** [comment]
why did you close the ticket without solving the problem?

**Comment by mikaelbr** [comment]
The issue isn't in this repo, but in https://github.com/mikaelbr/node-notifier/issues/208, and the progress is tracked there.

If you would like to have the issue open until the dependency is fixed we can do that.

**Comment by AlonBe** [comment]
If it helps someone, I just downgraded gulp-notify from v3.0.0 to the previous release (v2.2.0)
and now the notifications work for me on my very updated Windows 10

**Comment by vadim1884321** [comment]
On version 2.2.0 and windows 1709 "Fall Creator Update" pop-up notifications have earned! Thank AlonBe.

**Comment by amichel86** [comment]
@AlonBe is there a command way to downgrade the plugin or I need to uninstall it, and reinstall it with the 2.2.0 version?

**Comment by AlonBe** [comment]
@amichel86, I just did uninstall and install. Maybe there's a command for downgrading but it is a 5 seconds task so... :)

**Comment by mikaelbr** [comment]
This should have been fixed now. If it's still a problem, please repoen this issue.
