### ISSUE TITLE
not showing notifications on screen after a windows 10 update

### ISSUE THREAD

**Issue by Adrian-I** [mikaelbr/gulp-notify#125]
Hello.  About 2 months ago after a windows 10 update gulp-notify doesn't show up anymore (but it displays like it should  in the console ) . Right now i have win 10 pro version 10.0.16299 Build 16299 . Any idea what can i do ?
Thanks .

**Comment by mikaelbr** [comment]
There is some info on the issue here: https://github.com/mikaelbr/node-notifier/issues/144

**Comment by mikaelbr** [comment]
This should be fixed now.

**Comment by ngocsangyem** [comment]
Still, get this issue
