### ISSUE TITLE
gulp-notify not working on mac

### ISSUE THREAD

**Issue by Cratyz** [mikaelbr/gulp-notify#126]
I am not receiving a notification on Mac OSX 10.13.3

### Testcase
```
var gulp = require('gulp');
var notify = require('gulp-notify');
var notifier = require('node-notifier');
gulp.task('x', function() {
    // Not working
   notify('gulp-notify!');
});

gulp.task('y', function() {
    // Working
    notifier.notify('node-notifier');
})
```

Only the command `gulp y` creates a notification. I've installed the latest `gulp-notify` and the `require('node-notifier')` is the exact same module from `node_modules` dir as should be used by gulp-notify itself.

`npm list` shows:

`gulp-notify@3.2.0`
|--`node-notifier@5.2.1`

**Comment by mikaelbr** [comment]
Hi! The gulp-notify endpoint is a stream intended to be used in a gulp pipeline as seen here: https://github.com/mikaelbr/gulp-notify#usage

So what you are describing here is intended behavior. If you want to use it outside of a stream you can use node-notifier directly as with your second example.

**Comment by Cratyz** [comment]
oh ok i guess that makes sense. I have used this package in the past though (1-2y ago) where it _did_ work like this i believe

**Comment by mikaelbr** [comment]
Might it be that you're thinking of doing something like `notify.write()`? As it is a stream you can write vinyl files in object mode to the stream. Honestly, the API hasn't changed since 2014. 😛
