### ISSUE TITLE
Error runnning on Windows 8

### ISSUE THREAD

**Issue by rvlander** [mikaelbr/gulp-notify#57]
gulp-notify: [Error running notifier] Could not send message: Command failed:
Exception non g�r�e�: System.Exception: Exception de HRESULT : 0xC00CE508
   � Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   � toast.Program.ShowToast(String title, String message, String imageURI, Boolean sound)
   � toast.Program.Main(String[] args)

**Comment by gwynjudd** [comment]
Could it be due to console colours? I had a similar issue with gulp-typescript error handling, the error object was created with the message having embedded colour codes that caused the exact same error message. I resolved it by stripping the colours:

  ```var chalk = require('chalk');

js = result.js
	.on('error', function (error) {
		notify.onError({
			title: "Typescript compilation error",
			message: chalk.stripColor(error.message)
		})(error);
	})```

**Comment by rvlander** [comment]
I could (thank god) change my employers' mind and know I am allowed to use Archlinux. I won't be able to test it under windows anymore.
Sorry.

**Comment by fattakhov** [comment]
Running terminal with admin level has solved issue for me :+1:
thanks @peterblazejewicz

**Comment by mikaelbr** [comment]
Great! I've never noticed this issue as I always run with admin access (due to attaching debugger to iis process)

**Comment by operandom** [comment]
Hi!

I got the same problem and launch the command in admin doesn't solve the problem. : /

**Comment by operandom** [comment]
Ok, I think I got it: the ecape char made this error.

I add this lines to my code:
```javascript
var = isWin = /^win/.test(process.platform);

function escape(string) {
	return isWin ? string.replace(/\x1b/g, '') : string;
}
```

**Comment by mikaelbr** [comment]
Thanks. It might seem as the message given into the plugin has terminal colours, which crashes toaster. It's safe to filter this as toaster doesn't support these kind of colours anyways (not any notification system does), so it should be safe to filter it in any case.

I'll look into it as soon as I can, but patches are welcome. I think just filtering the message/title before sending it to `node-notifier` should suffice.
