### ISSUE TITLE
Toast messages on Windows 8.1 not working

### ISSUE THREAD

**Issue by thasmo** [mikaelbr/gulp-notify#61]
Hi there!

I've enabled notifications in the Windows settings, but messages just don't show up. Unfortunately I've no idea why and hope someone can help me.

In the notification settings it's possible to enable/disable notifications for applications separately. There's no option for node or gulp or npm etc. to enable/disable notifications. Could that be the reason? I was searching for a way to test toast notifications with another app/software, but I was not finding anything useful.

There's also no error so displaying/showing the toast notifications just fails silently (or they just don't show up for any reason).

Any idea how I can test if toast notifications work at all?

**Comment by thasmo** [comment]
I even don't get the error, it just fails silently. :l

**Comment by thasmo** [comment]
Ah, I got it running. Problem was that I didn't realize it only works when passed to a pipe function - I wanted to use `notify()` directly in a custom function, not wrapped within a pipe function.

**Comment by thasmo** [comment]
Is there a way to use `gulp-notify` directly, without using pipe? My use case is the following, and using `src('.')` is kind of a hack I want to avoid:
```js
gulp.task('scripts', ['scripts:common', 'scripts:vendor'], function() {
	gulp.src('.').pipe(notify('done'));
});

gulp.task('scripts:common', function() {
	// ...
});

gulp.task('scripts:vendor', function() {
	// ...
});
```

**Comment by mikaelbr** [comment]
You should look into running [node-notifier](https://github.com/mikaelbr/node-notifier) directly, as node-notifier is what gulp-notify uses internally. Here is an example of a person doing the switch: https://github.com/johnpapa/generator-hottowel/commit/6dcedd373ec8032272f943ba54b95a6c3601bfdc

**Comment by mikaelbr** [comment]
I'm closing this as it looks like it works now, @thasmo ? Just let me know if this isn't correct.

**Comment by adrianthedev** [comment]
I use a wrapper function 

> function n(message){
>        return gulp.src('.').pipe(notify(message));
> }

then just write n('message test');

**Comment by mikaelbr** [comment]
I'd say that's doing a lot of unnecessary work. Running `node-notifier` directly is the encouraged solution for this.

**Comment by adrianthedev** [comment]
It's true but as I see the `node-notifier` requires two parameters (`title` and `message`).
So it depends on what and how you use it for.

**Comment by mikaelbr** [comment]
`gulp-notify` is "higer level" than `node-notifier` and chooses a default title. You could do something like this:

```js
var notify = require('node-notifier');
var manualNotify(message) {
  return notify({
    title: 'My notification',
    message: message
  });
}
```

You wouldn't have the default icon and such, but you could also create your own set of defaults as it's done here: https://github.com/johnpapa/generator-hottowel/commit/6dcedd373ec8032272f943ba54b95a6c3601bfdc#diff-2e6ad34bed54ee43674888cab984c475R433

**Comment by adrianthedev** [comment]
Setting defaults does make more sence.
Thanks!
