### ISSUE TITLE
Notify on all errors?

### ISSUE THREAD

**Issue by altano** [mikaelbr/gulp-notify#62]
Can this be used to notify on all errors emitted, e.g. hook into gutil.PluginError() or something?

Or do I have to hook it up explicitly to anything that might throw an error that I want to notify on?

**Comment by mikaelbr** [comment]
You generally have to hook into every error, but there is a way of adding that for an entire pipeline (a task) using [gulp-plumber](https://github.com/floatdrop/gulp-plumber) (or something similar soon in "vanilla" gulp). You can see an example of this [in the readme](https://github.com/mikaelbr/gulp-notify#notestip).

There isn't any standardised way of doing this for all tasks in a gulpfile I'm afraid, but I think one can easily write some project-specific tool for doing it.
