### ISSUE TITLE
Allow callback function to return an object

### ISSUE THREAD

**Issue by gonsfx** [mikaelbr/gulp-notify#64]
I need to call notify using a callback to read information from the stream's vinyl file (jscs in my case).
I still want to be able to set title and other options beside message.

If we'd be allowed to return either a string or an object (string being the message only, options being an options object), i could so so.

**Comment by gonsfx** [comment]
Would you mind bumping the version to 2.1.1?

**Comment by mikaelbr** [comment]
I have one change that needs to be included as well. And the next version will be v2.2.0 as there are new functionality. Expect a version bump within maybe 12 hours.

**Comment by mikaelbr** [comment]
```shell
➜  gulp-notify git:(master) npm publish
+ gulp-notify@2.2.0
```

**Comment by gonsfx** [comment]
Great, thanks a lot!
