### ISSUE TITLE
How to debug for OSX

### ISSUE THREAD

**Issue by unphased** [mikaelbr/gulp-notify#70]
When I run gulp it leaves as many `terminal-notifier` processes running as there are files (such as CSS and JSX files) being processed, and there are a lot of them... Sometimes this precipitates "out of available file handles" issues with the operating system. It would appear (Just shooting from the hip here) that every time I edit and save a file some new process is spawned and failed to be cleaned -- after a nice heavy hack session of hundreds of file saves, something is bound to break.

So I have been using `DISABLE_NOTIFIER=true gulp` instead, which seems to not leave a billion `terminal-notifier`s hanging around. But this is not ideal because i can no longer see the messages that show me which files have just been changed (and just generally what gulp is up to). 

So I was hoping that someone here could help show me how I could get started troubleshooting what went wrong with my project's setup. Also possible is that i need to look at overall gulp config not just anything specific to gulp-notify.

**Comment by mikaelbr** [comment]
`gulp-notify` will create a notification for each of the files which are piped to it. If you pipe 100 vinyl files to it, it will create 100 notifications. You can choose to just emit once per stream though, by using the `onLast`-setting: https://github.com/mikaelbr/gulp-notify#optionsonlast

Hope that helps?

**Comment by unphased** [comment]
Well heres the other thing is that a few months ago I did see gulp generating system notifications when it was doing stuff, but none of that is happening. I get zero system notifications and these `terminal-notifier` processes are just piling up. My assumption was that this *cannot* **possibly** be expected behavior. I'll look into that option, thanks.

**Comment by mikaelbr** [comment]
Usually you would use `gulp-notify` after doing some minification/concatination, so you would only pipe one file.

**Comment by unphased** [comment]
I still wanna see the messages for each file though. Is there a way to make a config option that disables the notification but still shows th per-file message?

**Comment by mikaelbr** [comment]
Ah, so you want to show message in terminal, but not get notification in Notification Center? I think the best way for that is to simply log the files.

Something like this:

```js
gulp.src('./**/*.js')
  // .pipe(somePlugin()) // do something with stream
  .on('data', function (file) {
   console.log('File: ', file.relative);
  });
```

You can make it prettier using something like https://github.com/sindresorhus/chalk or use [gutils.log](https://github.com/gulpjs/gulp-util#logmsg) (though I think that might be deprecated in time).

**Comment by unphased** [comment]
I find that running terminal-notifier like this: 

```
./node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier -
message 'test'
```

it just hangs, leaving a node process consuming 5+MB of RAM. This is the root of the issue.

**Comment by mikaelbr** [comment]
That's weird. Does it go away in time (i.e. ~30 seconds)?

**Comment by unphased** [comment]
No, it never returns.

**Comment by mikaelbr** [comment]
And you see no notification?

**Comment by unphased** [comment]
Yeah it's just clearly borked

**Comment by unphased** [comment]
I tried something like the snippet you suggested, what it receives inside `on()` is a raw buffer for the file content. Which is.... nice? But I rather like the nice colored templatable `message` i set for the notify options...

**Comment by unphased** [comment]
https://github.com/alloy/terminal-notifier/issues/115 

This is the issue. It actually works when not under tmux. 

Solved.

**Comment by mikaelbr** [comment]
Thanks for figuring it out!
