### ISSUE TITLE
Disable Windows tray notification

### ISSUE THREAD

**Issue by snaveenkumareee** [mikaelbr/gulp-notify#79]
the notifier is getting delayed because of the tray notification. can you please help me disabling the windows tray notification.
my env details:
windows 7 64 bit.
"gulp": "^3.8.11",
"gulp-notify": "^2.2.0",

**Comment by mikaelbr** [comment]
You can see information about how to disable `gulp-notify` here: https://github.com/mikaelbr/gulp-notify#disable-gulp-notify
