### ISSUE TITLE
Command failed: libnotify-Message

### ISSUE THREAD

**Issue by usandfriends** [mikaelbr/gulp-notify#88]
I get the following error after the notification is logged when I run `gulp` through SSH:

    [19:58:36] gulp-notify: [Gulp notification] [main] styles task complete
    [19:58:36] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
    Message:
        Command failed: libnotify-Message: Unable to get session bus: dbus-launch failed to autolaunch D-Bus session: Fd 10 did not have the close-on-exec flag set!  Setting the flag. Fd 13 did not have the close-on-exec flag set!  Setting the flag.

    Details:
        killed: false
        code: 1
        signal: null

Here is the code that is failing:

    .pipe(notify({ message: '[main] styles task complete', onLast: true }));

**Comment by usandfriends** [comment]
Is there any way to silence the error?

**Comment by mikaelbr** [comment]
This is probably due to it not being able to access notify-send through SSH the channel. You can disable it on your enviroment by using env variables. Read more about it here: https://github.com/mikaelbr/gulp-notify#disable-gulp-notify

**Comment by usandfriends** [comment]
That disabled output completely. I would still like to keep the output, just ignore the error.

**Comment by mikaelbr** [comment]
As for now there's no way to disable notification but still have the terminal output. I'd suggest to either just listen for data and do `console.log` yourself, or use [.withReporter](https://github.com/mikaelbr/gulp-notify#notifywithreporterfunction) to mute the notification.

**Comment by usandfriends** [comment]
I think I'll go the `.withReporter` route. Thanks!
