### ISSUE TITLE
Windows 10 notifications not working

### ISSUE THREAD

**Issue by vdecree** [mikaelbr/gulp-notify#90]
Hi there,

Does anyone know if this is supposed to work on Windows 10? I'm not getting any notifications. They're appearing in the new 'action centre' but not popping up as notifications as per other applications.

**Comment by mikaelbr** [comment]
Hi!

I haven't gotten to test this yet with Windows 10. But given if the toast implementation isn't changed too much it should be possible. I don't have Windows 10 yet, so I'm not able to test it out, I'm afraid. But hopefully someone can dig into what's causing this.

Have you tried running [toaster](https://github.com/nels-o/toaster) manually, to see if you get any output?

Perhaps there's a setting in the new Windows for activating notifications, as it is visible in the "action centre"?

**Comment by vdecree** [comment]
Hi @mikaelbr,

Thanks for the prompt reply! 

I've not tried running it manually, although I will do. Looking through all the notification settings on the new OS and it looks as though everything is on. I've tried numerous things but nothing seems to have worked yet. 

Hoping someone more in the know can help us find a solution.

**Comment by mikaelbr** [comment]
One thing that could potentially be causing this is change in what apps are allowed to do notifications. Previously you [had to have a shortcut on the start screen](https://github.com/nels-o/toaster#deps).

**Comment by mikaelbr** [comment]
For anyone with access to Visual Studio and Windows 10: Should try to run [toaster project](https://github.com/nels-o/toaster) in VS and see if any changes needs to be made. Could compare with this [Windows 10 toaster guide](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx)

**Comment by lawsonk1215** [comment]
+1
Like mentioned above, notifications show in the action center but aren't being shown as popup. Since the notification is a toast, you shouldn't have to allow an app. Toasts are allowed by default and can be changed in the settings.

**Comment by vdecree** [comment]
Yes,  I've checked the settings and it appears toast is active.

**Comment by name-k** [comment]
I have same problem on Windows 10, but notifications worked well in first three days of using new OS, and then just stopped popping up, without any changes in the settings.

**Comment by ionutz2k2** [comment]
It's a Windows configuration issue. You can make it work by going to System > Notifications & Actions. The 'toast' app needs to have Banners enabled. (You can activate banners by clicking on the 'toast' app and setting the 'Show notification banners' to On)

**Comment by mikaelbr** [comment]
Interesting! Does that work for you, @name-k , @vdecree and @lawsonk1215 ?

**Comment by vdecree** [comment]
I can confirm that seems to have worked. It's very unclear with the new UI. You actually have to click on the Toast app name in the settings, which will reveal three more options, one of which i the 'Show notification banners'. This can be switched to on and I am now getting the notifications on screen. Really happy now, thank you @ionutz2k2.

**Comment by lawsonk1215** [comment]
Yea I just checked. thanks @ionutz2k2. Windows should probably make it more noticeable but whatever.

**Comment by ionutz2k2** [comment]
You're welcome. I'm glad I could help.

**Comment by vdecree** [comment]
@lawsonk1215 Typical Microsoft UI fails, as ever. Good job we have people in the know!

**Comment by mikaelbr** [comment]
Good work, all! Closing this. Thanks :cake:

**Comment by fritx** [comment]
I can't find the 'toast' app from the list..

**Comment by matthewdaniel** [comment]
me neither

**Comment by mikaelbr** [comment]
This will hopefully change when this is merged: https://github.com/mikaelbr/node-notifier/pull/134

Stay tuned!

**Comment by eujeniogonzalez** [comment]
> It's a Windows configuration issue. You can make it work by going to System > Notifications & Actions. The 'toast' app needs to have Banners enabled. (You can activate banners by clicking on the 'toast' app and setting the 'Show notification banners' to On)

It's really works! Thank you! It never occurred to me that the problem was on the Windows 10 side.
