### ISSUE TITLE
Can not to off notify

### ISSUE THREAD

**Issue by artem-malko** [mikaelbr/gulp-notify#93]
```javascript
notify.logLevel(0);
return notify();
````
notify is returned to pipe.
So, this example is not working, notifier still shows all notifies in System (OS X)

**Comment by mikaelbr** [comment]
Log-level isn't to turn off notification, it is to turn of logging. See [Disable gulp-notify](https://github.com/mikaelbr/gulp-notify#disable-gulp-notify) for how to disable it.

**Comment by artem-malko** [comment]
Ok, but where should I write export DISABLE_NOTIFIER=true; ?

**Comment by mikaelbr** [comment]
It's a [environment variable](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x). Easies is to instead of doing

```shell
gulp myTaskName
```

you do

```shell
export DISABLE_NOTIFIER=true; gulp myTaskName
```

**Comment by artem-malko** [comment]
So, I can turn off system messages (in top right corner of the screen) by using DISABLE_NOTIFIER, can't I? But why loglevel does not off notifications in system?

**Comment by mikaelbr** [comment]
> So, I can turn off system messages (in top right corner of the screen) by using DISABLE_NOTIFIER, can't I? 

Yes, that's correct.

> But why loglevel does not off notifications in system?

**Log** level is for **log**ging, not notification.

**Comment by artem-malko** [comment]
Thank you, it is clear for me now)

**Comment by mikaelbr** [comment]
Great! Glad it worked out.

**Comment by artem-malko** [comment]
I've solved my problem with another approach)
I return notifier to a pipe in all my tasks and I have got simple helper for notifier. So, when notifier is on (notifyConfig.useNotify) I return notifier and if it is off, I return gutil.noop()
````javascript
if (notifyConfig.useNotify) {
        return notify({
            onLast: onLast || true,
            sound: notifyConfig.sounds.onSuccess,
            title: notifyConfig.title,
            message: resultMessage,
            templateOptions: {
                date: modifyDate.getTimeOfModify()
            }
        });
    } else {
        return gutil.noop();
    }
````
Maybe it can be usefull for you in #80 implementing.

**Comment by mikaelbr** [comment]
You can also use `gulp-if` to do this.

Something like:
```js
gulp.src(..)
  .pipe(gulpIf(notifyConfig.useNotify, notify({
        onLast: onLast || true,
        sound: notifyConfig.sounds.onSuccess,
        title: notifyConfig.title,
        message: resultMessage,
        templateOptions: {
            date: modifyDate.getTimeOfModify()
        }
    })
...
```

**Comment by artem-malko** [comment]
Yes, but I thought, that gutil.noop() will be helpful in silent mode implementing.
